/*
MySQL Data Transfer
Source Host: localhost
Source Database: conferen_conferen
Target Host: localhost
Target Database: conferen_conferen
Date: 16/08/2010 1:44:12 CH
*/

SET FOREIGN_KEY_CHECKS=0;
-- ----------------------------
-- Table structure for confor_email_templates
-- ----------------------------
CREATE TABLE `confor_email_templates` (
  `id` int(5) NOT NULL AUTO_INCREMENT,
  `code` varchar(10) DEFAULT NULL,
  `name` varchar(200) NOT NULL,
  `subject` varchar(255) NOT NULL,
  `body` text,
  `lang` varchar(5) NOT NULL DEFAULT 'en',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=13 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records 
-- ----------------------------
INSERT INTO `confor_email_templates` VALUES ('1', 'VS', 'Video Suppression', 'Video Suppression', 'Welcome [USERNAME]! Thanks for registering.\r\n---------------------------------------------------\r\n\r\nHello,\r\n\r\nYou\'re now a member of [SITE_NAME].\r\n\r\nHere are your login details. Please keep them in a safe place:\r\n\r\nUsername: [USERNAME]\r\nPassword: [PASSWORD]\r\n\r\n---------------------------------------------------\r\n\r\nThe administrator of this site has requested all new accounts\r\nto be activated by the users who created them thus your account\r\nis currently inactive. To activate your account,\r\nplease visit this link:\r\n[LINK]\r\n\r\nThanks,\r\n[SITE_NAME] Team\r\n[URL]', 'en');
INSERT INTO `confor_email_templates` VALUES ('2', 'AS1', 'Account Suppression', 'Account Suppression', 'New password reset from [SITE_NAME]!\r\n---------------------------------------------------------------------------------------------------------\r\n\r\nHello, [USERNAME]\r\n\r\nIt seems that you or someone requested a new password for you.\r\n\r\nWe have generated a new password, as requested:\r\n\r\nYour new password: [PASSWORD]\r\n\r\n\r\nTo use the new password you need to activate it. To do this click the link provided below and login with your new password.\r\n[LINK]\r\n\r\nYou can change your password after you sign in.\r\n\r\nThanks,\r\n[SITE_NAME] Team\r\n[URL]\r\n\r\n---------------------------------------------------------------------------------------------------------\r\nPassword requested from IP: [IP]', 'en');
INSERT INTO `confor_email_templates` VALUES ('3', 'AS2', 'Account Suspension', 'Account Suspension', 'Welcome [NAME]! Thanks for registering.\r\n---------------------------------------------------------------------------------------------------------\r\n\r\nHello,\r\n\r\nYou\'re now a member of [SITE_NAME].\r\n\r\nHere are your login details. Please keep them in a safe place:\r\n\r\nUsername: [USERNAME]\r\nPassword: [PASSWORD]\r\n\r\n\r\n---------------------------------------------------------------------------------------------------------\r\nThanks,\r\n[SITE_NAME] Team\r\n[URL]', 'en');
INSERT INTO `confor_email_templates` VALUES ('4', 'BAU', 'Bronzes Account Update', 'Bronzes Account Update', 'Hello,\r\n[USERNAME]\r\nYou are receiving this email as a part of your newsletter subscription\r\n\r\n---------------------------------------------------------------------------------------------------------\r\n\r\nHere goes your newsletter content\r\n\r\n---------------------------------------------------------------------------------------------------------\r\n\r\nThanks,\r\n[SITE_NAME] Team\r\n[URL]\r\n---------------------------------------------------------------------------------------------------------\r\nTo stop receiving future newsletters please login into your account\r\nand uncheck newsletter subscription box.', 'en');
INSERT INTO `confor_email_templates` VALUES ('5', 'SAU', 'Silver Account Update', 'Silver Account Update', 'Hello, Admin\r\n\r\nYou have received new PayPal payment following:\r\n\r\n---------------------------------------------------------------------------------------------------------\r\n\r\nUsername: [USERNAME]\r\nItem: [ITEMNAME]\r\nPrice: [PRICE]\r\n\r\nStatus: [STATUS] \r\n\r\n---------------------------------------------------------------------------------------------------------\r\nYou can view this transaction from [URL]', 'en');
INSERT INTO `confor_email_templates` VALUES ('6', 'GAU', 'Gold Account Update', 'Gold Account Update', 'Hello, Admin\r\n----------------------------------------------------------\r\nThe following transaction has been disabled due to suspicious activity:\r\n\r\nBuyer: [USERNAME]\r\nItem: [ITEM]\r\nPrice: [PRICE]\r\nStatus: [STATUS]\r\n\r\n----------------------------------------------------------\r\nPlease verify this transaction is correct. If it is, please activate it in the transaction section of your site\'s \r\nadministration control panel. If not, it appears that someone tried to fraudulently obtain products from your site.', 'en');
INSERT INTO `confor_email_templates` VALUES ('7', 'VS', 'Video Suppression(fr)', 'Video Suppression(fr)', 'Welcome [USERNAME]! Thanks for registering.\n---------------------------------------------------\n\nHello,\n\nYou\'re now a member of [SITE_NAME].\n\nHere are your login details. Please keep them in a safe place:\n\nUsername: [USERNAME]\nPassword: [PASSWORD]\n\n---------------------------------------------------\n\nThe administrator of this site has requested all new accounts\nto be activated by the users who created them thus your account\nis currently inactive. To activate your account,\nplease visit this link:\n[LINK]\n\nThanks,\n[SITE_NAME] Team\n[URL]', 'fr');
INSERT INTO `confor_email_templates` VALUES ('8', 'AS1', 'Account Suppression(fr)', 'Account Suppression(fr)', 'New password reset from [SITE_NAME]!\n---------------------------------------------------------------------------------------------------------\n\nHello, [USERNAME]\n\nIt seems that you or someone requested a new password for you.\n\nWe have generated a new password, as requested:\n\nYour new password: [PASSWORD]\n\n\nTo use the new password you need to activate it. To do this click the link provided below and login with your new password.\n[LINK]\n\nYou can change your password after you sign in.\n\nThanks,\n[SITE_NAME] Team\n[URL]\n\n---------------------------------------------------------------------------------------------------------\nPassword requested from IP: [IP]', 'fr');
INSERT INTO `confor_email_templates` VALUES ('9', 'AS2', 'Account Suspension(fr)', 'test', 'Welcome [NAME]! Thanks for registering.\n---------------------------------------------------------------------------------------------------------\n\nHello,\n\nYou\'re now a member of [SITE_NAME].\n\nHere are your login details. Please keep them in a safe place:\n\nUsername: [USERNAME]\nPassword: [PASSWORD]\n\n\n---------------------------------------------------------------------------------------------------------\nThanks,\n[SITE_NAME] Team\n[URL]', 'fr');
INSERT INTO `confor_email_templates` VALUES ('10', 'BAU', 'Bronzes Account Update(fr)', '', null, 'fr');
INSERT INTO `confor_email_templates` VALUES ('11', 'SAU', 'Silver Account Update(fr)', 'Silver Account Update(fr)', 'Welcome [NAME]! Thanks for registering.\n---------------------------------------------------------------------------------------------------------\n\nHello,\n\nYou\'re now a member of [SITE_NAME].\n\nHere are your login details. Please keep them in a safe place:\n\nUsername: [USERNAME]\nPassword: [PASSWORD]\n\n\n---------------------------------------------------------------------------------------------------------\nThanks,\n[SITE_NAME] Team\n[URL]', 'fr');
INSERT INTO `confor_email_templates` VALUES ('12', 'GAU', 'Gold Account Update(fr)', 'Gold Account Update(fr)', 'Welcome [NAME]! Thanks for registering.\n---------------------------------------------------------------------------------------------------------\n\nHello,\n\nYou\'re now a member of [SITE_NAME].\n\nHere are your login details. Please keep them in a safe place:\n\nUsername: [USERNAME]\nPassword: [PASSWORD]\n\n\n---------------------------------------------------------------------------------------------------------\nThanks,\n[SITE_NAME] Team\n[URL]', 'fr');
